Importing Numpy Library

In [1]:
import numpy as np

**Matrix Addition**

In [2]:
# Creating two matrices

A = np.array([[2,3],[4,5]])

B = np.array([[6,7],[8,9]])

In [3]:
print(A)
A.shape

[[2 3]
 [4 5]]


(2, 2)

In [4]:
print(B)
B.shape

[[6 7]
 [8 9]]


(2, 2)

**Adding Matrices**

In [5]:
sum = A + B
print(sum)

[[ 8 10]
 [12 14]]


In [6]:
# Create two matrices with random values
matrix_1 = np.random.randint(10, size=(3,3))
matrix_2 = np.random.randint(20, size=(3,3))


In [7]:
print(matrix_1)

[[3 0 4]
 [6 7 2]
 [7 3 4]]


In [8]:
print(matrix_2)

[[ 7 12  8]
 [15  7 14]
 [ 4 15  0]]


In [9]:
sum = np.add(matrix_1, matrix_2)

In [10]:
print(sum)

[[10 12 12]
 [21 14 16]
 [11 18  4]]


In [11]:
# Create two matrices with random values
matrix_3 = np.random.randint(10, size=(3,3))
matrix_4 = np.random.randint(20, size=(3,4))

In [12]:
sum_2 = np.add(matrix_3, matrix_4)

ValueError: operands could not be broadcast together with shapes (3,3) (3,4) 

We get this error because shape of matrix_3 and matrix_4 are different

**Matrix Subtraction**

In [13]:
# Creating two matrices

A = np.array([[2,3],[4,5]])

B = np.array([[6,7],[8,9]])

In [14]:
print(A)

[[2 3]
 [4 5]]


In [15]:
print(B)

[[6 7]
 [8 9]]


In [16]:
difference = A - B

In [17]:
print(difference)

[[-4 -4]
 [-4 -4]]


In [18]:
# Create two matrices with random values
matrix_1 = np.random.randint(10, size=(3,3))
matrix_2 = np.random.randint(20, size=(3,3))

In [19]:
print(matrix_1)

[[7 6 5]
 [9 1 3]
 [3 8 3]]


In [20]:
print(matrix_2)

[[18 16  5]
 [16  1 14]
 [ 8  3 14]]


In [21]:
diff = np.subtract(matrix_1, matrix_2)

In [22]:
print(diff)

[[-11 -10   0]
 [ -7   0 -11]
 [ -5   5 -11]]


**Multiplying a matrix by a scalar**

In [23]:
x = 5
y = np.random.randint(10, size=(4,4))

print(y)

[[5 2 3 3]
 [8 4 0 8]
 [9 2 1 7]
 [2 5 3 9]]


In [24]:
product = np.multiply(x,y)

In [25]:
print(product)

[[25 10 15 15]
 [40 20  0 40]
 [45 10  5 35]
 [10 25 15 45]]


**Multiplying 2 Matrices**

In [26]:
# create two matrices with random values
matrix_3 = np.random.randint(5, size=(3,3))
matrix_4 = np.random.randint(5, size=(3,4))

In [27]:
print(matrix_3)

[[2 0 2]
 [2 1 2]
 [2 0 3]]


In [28]:
print(matrix_4)

[[2 1 1 2]
 [3 4 4 3]
 [0 1 1 2]]


In [29]:
product = np.dot(matrix_3, matrix_4)

In [30]:
print(product)

[[ 4  4  4  8]
 [ 7  8  8 11]
 [ 4  5  5 10]]


In [31]:
product.shape

(3, 4)

In [32]:
# Create two matrices with random values
matrix_3 = np.random.randint(5, size=(3,3))
matrix_4 = np.random.randint(5, size=(4,4))

In [33]:
product = np.dot(matrix_3, matrix_4)

ValueError: shapes (3,3) and (4,4) not aligned: 3 (dim 1) != 4 (dim 0)

**Element wise Matrix Multiplication**

In [34]:
# Create two matrices with random values
matrix_3 = np.random.randint(5, size=(3,3))
matrix_4 = np.random.randint(5, size=(3,3))

In [35]:
print(matrix_3)

[[2 3 0]
 [3 4 1]
 [4 1 0]]


In [36]:
print(matrix_4)

[[1 1 2]
 [2 0 3]
 [0 1 4]]


In [37]:
product = np.multiply(matrix_3, matrix_4)

In [ ]:
print(product)

[[ 1  0  2]
 [ 4  6 12]
 [ 0  0  8]]


In [50]:
# Create two matrices with random values
matrix_3 = np.random.randint(5, size=(4,3))
matrix_4 = np.random.randint(5, size=(4,3))

In [51]:
product = np.multiply(matrix_3, matrix_4)
print (product)

[[4 0 0]
 [4 0 0]
 [0 9 0]
 [8 4 0]]
