In [7]:
import time
import numpy as np

In [3]:
#Time 
start = time.time()

a = [i for i in range(100000000)]
b = [i for i in range(100000000, 200000000)]
c = []

for i in range(len(a)):
    c.append(a[i] + b[i])

print (len(a))
print(time.time() - start)


100000000
26.914185762405396


In [ ]:
#Numpy
start = time.time()

a = np.arange(100000000)
b = np.arange(100000000, 200000000)
c = a + b

print(time.time() - start)


1.0268402099609375


Arrays

In [ ]:
#Numpy Array
numpy_array = np.array([1,2,3]) # One Dimensional 
print(numpy_array) 
numpy_array_2 = np.array([[1,2],[4,5],[4,2]]) # Multi Dimensional
print(numpy_array_2)
print("Datatype =", numpy_array_2.dtype)
print("Shape =",numpy_array_2.shape)
print("Size =",numpy_array_2.size)
print("Dimension =",numpy_array_2.ndim) 


[1 2 3]
[[1 2]
 [4 5]
 [4 2]]
Datatype = int64
Shape = (3, 2)
Size = 6
Dimension = 2


In [22]:
#All Zeros 
zeros = np.zeros((2,3),dtype=int) # dtype for change type
print(zeros, "\n", zeros.dtype) 
#All Ones
ones = np.ones((3,3),dtype=int) # dtype for change type
print(ones, "\n", ones.dtype) 


[[0 0 0]
 [0 0 0]] 
 int64
[[1 1 1]
 [1 1 1]
 [1 1 1]] 
 int64


In [43]:
# 1st code: np.arange(11)
arr_r = np.arange(11)  # Creates an array of integers from 0 to 10 (11 is excluded)
print(arr_r)  


# 2nd code: np.linspace(1, 5, 10)
arr_d = np.linspace(1, 5, 10)  
# Creates 10 evenly spaced numbers between 1 and 5 (inclusive)
"""The range is from 1 to 5, which is a difference of 4. 
We need 10 numbers, so there are 9 intervals (since 10 elements create 9 gaps). 
Step size = 4 / 10 ≈ 0.44444444. 
Numbers generated: 1, 1 + 0.4444, 1 + 2*0.4444, 1 + 3*0.4444, ..., 1 + 9*0.4444"""
print(arr_d) 

[ 0  1  2  3  4  5  6  7  8  9 10]
[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]
